name: doodler-dev-test
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.7
 - CairoSVG
 - matplotlib
 - scipy
 - numpy
 - scikit-image
 - Pillow
 - scikit-learn
 - cairo
 - tqdm
 - psutil
 - jupyterlab
 - holoviews
 - panel
 - flake8
 - pytest
 - pytest-cov
 - pip
 - pip:
   - git+https://github.com/li-plus/pydensecrf.git@0d53acbcf5123d4c88040fe68fbb9805fc5b2fb9
